Update

diff --git a/shell-scripts/mbin-scripts/task b/shell-scripts/mbin-scripts/task
--- a/shell-scripts/mbin-scripts/task
+++ b/shell-scripts/mbin-scripts/task
@@ -1,36 +1,39 @@
 #!/bin/sh
 set -eu
-[ "$#" -eq 0 ] && exit 1
-FILE="$HOME"/.tasks
+
+print_error() { echo "${0##*/}: Error: $1" ; }
+
+FILE="$HOME/.tasks"
 TASK_ID='t:'
 CATEGORY_ID='c:'
-detect_bad_statement()
-{
-	if grep -q "$1" "$FILE"; then
-		echo "Error: bad statement \"$1\" in tasks file, remove it"
-		exit 1
-	fi
-}
-check_if_arg_provided()
-{
-	if [ "$#" -ne "$1" ]; then
-		echo "Error: argument number $1 not provided"
-		exit 1
-	fi
-}
-detect_bad_statement "^${CATEGORY_ID}all$"
-case "$1" in
-	add) echo "${TASK_ID}$2" >> "$FILE" ;;
-	category)
-		case "$2" in
-			add) check_if_arg_provided 3 && echo "${CATEGORY_ID}$2" >> "$FILE" ;;
-			del) check_if_arg_provided 3 &&
-		esac
-	;;
-	list)
-		case "$2" in
-			all) cat "$FILE" ;;
-			*)
 
-	*) exit 1 ;;
+grep -m1 -qvE "^($TASK_ID|$CATEGORY_ID)" "$FILE" && {
+	print_error 'bad file, clean it'
+	exit 1
+}
+
+[ "$#" -eq 0 ] && exit 1
+
+case "$1" in
+
+	a|a,t)
+		NUM="$(grep -n "${CATEGORY_ID}$2" "$FILE" | cut -d':' -f1)" || {
+			print_error "category \"$2\" not found"
+			exit 1
+		}
+
+		sed -i "${NUM}a ${TASK_ID}$3" "$FILE"
+	;;
+
+	a,c)
+		grep -q "${TASK_ID}$2" "$FILE" && {
+			print_error "category \"$2\" already exists"
+			exit 1
+		}
+
+		echo "${TASK_ID}$2" >> "$FILE"
+	;;
+
+	*) print_error "argument \"$1\" not recongnized" && exit 1 ;;
+
 esac
