Update

diff --git a/tor-scripts/keep-tor-alive b/tor-scripts/keep-tor-alive
--- a/tor-scripts/keep-tor-alive
+++ b/tor-scripts/keep-tor-alive
@@ -2,6 +2,8 @@
 
 set -eu
 
+[ "$(id -u)" -ne 0 ] && echo 'Error: you must be root' 1>&2 && exit 1
+
 LOG_FILE="/var/log/$(basename "$0").log"
 
 printf '' > "$LOG_FILE"
@@ -20,11 +22,11 @@ while true; do
 	
 		if env -i su nobody -s /bin/sh -c "curl --silent -L --socks5 $socks5_address 'https://html.duckduckgo.com' 1>/dev/null"; then
 
-			echo "$(date "$DATE_PATTERN") curl Success" >> "$LOG_FILE"
+			echo "$(date "$DATE_PATTERN") curl for $socks5_address Succeeded" >> "$LOG_FILE"
 
 		else
 
-			echo "$(date "$DATE_PATTERN") curl Failed" >> "$LOG_FILE"
+			echo "$(date "$DATE_PATTERN") curl for $socks5_address Failed" >> "$LOG_FILE"
 
 		fi
 	
