Update

diff --git a/shell-scripts/X-scripts/dmenu-exec-command b/shell-scripts/X-scripts/dmenu-exec-command
--- a/shell-scripts/X-scripts/dmenu-exec-command
+++ b/shell-scripts/X-scripts/dmenu-exec-command
@@ -3,25 +3,19 @@
 set -eu
 
 COMMAND="$(dmenu < /dev/null)"
-
 [ -z "$COMMAND" ] && exit 0
 
-PROGRAM="$(echo "$COMMAND" | cut -d' ' -f1)"
-
-if ! command -v "$PROGRAM" 1>/dev/null 2>&1; then
-
-	notify-send "Error: command \"$PROGRAM\" not found"
-
+EXE="${COMMAND%% *}"
+command -v "$EXE" 1>/dev/null 2>&1 || {
+	notify-send "[ERROR]: executable \"$EXE\" not found"
 	exit 1
-
-fi
-
-OUTPUT="$(eval $COMMAND 2>&1)" || {
-
-	notify-send "$(printf 'Command "%s" exited with exit code "%i", output:\n%s' "$COMMAND" "$?" "$OUTPUT")"
-
-	exit 1
-
 }
 
-notify-send "$OUTPUT"
+[ "$#" -eq 1 ] && [ "$1" = '-s' ] && exec eval "$COMMAND"
+
+OUTPUT="$(eval "$COMMAND" 2>&1)" || {
+	notify-send "$(printf '[ERROR]: command "%s" exited with exit code "%i", output:\n%s' "$COMMAND" "$?" "$OUTPUT")"
+	exit 1
+}
+
+exec notify-send "$OUTPUT"
